version: '3'

services:
  order-service:
    image: python:alpine3.10

  mail-service:
    image: python:alpine3.10

  product-service:
    image: wiremock/wiremock:2.32.0-alpine
    command: --verbose
    volumes:
      - ./wiremock/product-service/stubs:/home/wiremock
    ports:
    - "8081:8080"

  user-service:
    image: wiremock/wiremock:2.32.0-alpine
    command: --verbose
    volumes:
      - ./wiremock/user-service/stubs:/home/wiremock
    ports:
    - "8082:8080"

  mail-provider:
    image: wiremock/wiremock:2.32.0-alpine
    command: --verbose
    volumes:
      - ./wiremock/mail-provider/stubs:/home/wiremock
    ports:
    - "8083:8080"

  rabbitmq:
    image: rabbitmq:3.10.0-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=hellofresh
      - RABBITMQ_DEFAULT_PASS=food
    ports:
      - "5672:5672"
      - "15672:15672"
